### ISSUE TITLE
Comment on /generate-eleventy-posts-with-hygen/

### ISSUE THREAD

**Issue by davidrhoden** [joshcanhelp/josh-to-11#44]
Boilerplate fatigue: thanks for the term. I have the same issue with copy/paste errors on my Eleventy site (usually omitting a space after a colon in the front matter, which breaks the build).

I'm going to try to install this; I could really use it.

https://davidrhoden.com (my Eleventy site)

**Comment by joshcanhelp** [comment]
@davidrhoden - Appreciate the comment, David! If you find any issues with the post or instructions within, feel free to let me know here or submit a PR 🙇
